version: "3.0"

services:


  # ELK Stack Config
  # elasticsearch:
  #   env_file: env
  #   build:
  #     context: ../elasticsearch/
  #     args:
  #       ELK_VERSION: 6.4.0
  #   volumes:
  #     - ../elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk

  # logstash:
  #   env_file: env
  #   build:
  #     context: ../logstash/
  #     args:
  #       ELK_VERSION: 6.4.0
  #   volumes:
  #     -  ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     -  ../logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  # kibana:
    # env_file: env
    # build:
    #   context: ../kibana/
    #   args:
    #     ELK_VERSION: 6.4.0
    # volumes:
    #   -  ../kibana/config/:/usr/share/kibana/config:ro
    # ports:
    #   - "5601:5601"
    # networks:
    #   - elk
    # depends_on:
    #   - elasticsearch

  # Kafka

  kafka:
    image: landoop/fast-data-dev
    labels:
      - "traefik.enable=true"   
      - "traefik.fastdata.backend=fastdata"
      - "traefik.fastdata.port=3030"
      - "traefik.kafkabroker.backend=kafkabroker"
      - "traefik.kafkabroker.port=9092"
      - "traefik.schemaregistry.backend=schemaregistry"
      - "traefik.schemaregistry.port=8081"
      - "traefik.kafkarest.backend=kafkarest"
      - "traefik.kafkarest.port=8082"
      - "traefik.kafkaconnect.backend=kafkaconnect"
      - "traefik.kafkaconnect.port=8083"
      - "traefik.zookeeper.backend=zookeeper"
      - "traefik.zookeeper.port=2181"

  # E2E Testing (API)
  api-tests:
    build:
      context: ../..
    image: node:10-alpine
    expose:
      - "3080"
    ports:
      - "3080:3080"
    env_file: env
    environment:
      LOGLEVEL: debug
      PORT: 3080

    working_dir: /services
    volumes:
      - ../..:/services

    command: /bin/sh -c "npm install && npm run api-tests"
  
    links:
      - api
    depends_on:
      - api

    labels:
      - "traefik.enable=true"  
      - "traefik.port=3080"
      - "traefik.backend=api-tests"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  # Load Testing

  
  # Moleculer Config
  api:
    build:
      context: ./../..
    image: node:10-alpine
    expose:
      - "3050"
    ports:
      - "3050:3050"
    env_file: env
    environment:
      LOGLEVEL: debug
      PORT: 3050

    working_dir: /src
    volumes:
      - ../..:/src

    command: /bin/sh -c "npm install && npm run start-api"
    
    links:
      - nats
      - mongo
      - redis
    depends_on:
      - nats
      - mongo
      - redis
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3050"
      - traefik.backend.healthcheck.path=/~node/health

  core:
    build:
      context: ./../..
    image: node:10-alpine
    env_file: env
    environment:
      LOGLEVEL: debug

    working_dir: /src
    volumes:
      - ../..:/src

    command: /bin/sh -c "npm install && npm run start-core"
    
    links:
      - nats
      - mongo
      - redis
      - kafka
    depends_on:
      - nats
      - mongo
      - redis
      - kafka
    labels:
      - "traefik.enable=false"
  
  redis:
    image: redis:alpine

  mongo:
    image: mongo

  nats:
    image: nats

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

networks:
  elk:
    driver: bridge