global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: api-service
    static_configs:
      - targets: ['api-service:3060']
  - job_name: core-service
    static_configs:
      - targets: ['core-service:3061']